name: docker

on:
  push:
    branches:
      - master
      - develop
      - fix-cd-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get image tag
      id: prepare
      uses: Surgo/docker-smart-tag-action@v1
      with:
        docker_image: 'docker.pkg.github.com/surfriderfoundationeurope/labelcv-web/labelcv-web'
    - name: Login to GitHub Packages
      run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - name: Build docker image
      run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.prepare.outputs.tag }}
    # - name: Push to GitHub Packages
    #   run: docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.prepare.outputs.tag }}