name: docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: docker build -t labelcv .
    # TODO: Consider deploying image.